# Controller: DualShock 4
joy_to_base_cmd:
  ros__parameters:
    axis_forward: 5
    axis_backward: 2
    axis_steer: 0
    axis_spin: 3
    scale_forward: 0.1
    scale_backward: 0.1
    scale_steer: 1.0
    scale_spin: 0.1
    deadzone_forward: 0.1
    deadzone_backward: 0.1
    deadzone_steer: 0.1
    deadzone_spin: 0.2
