joy_to_cmd_vel:
  ros__parameters:
    base_enable_button: 5
    axis_linear: 1
    axis_angular_turn: 0
    axis_angular_rot: 3
    scale_linear: 0.1
    scale_angular_turn: 0.1
    scale_angular_rot: 0.1
    deadzone_linear: 0.1
    deadzone_angular_turn: 0.1
    deadzone_angular_rot: 0.2
